import * as jsYaml from "js-yaml";
import * as fs from "fs";
import * as path from "path";

import { promisify } from "util";
import * as logger from "../util/logger";
import { ActionYml, InputOutputEntries, InputOrOutput } from "./types";

// eslint-disable-next-line function-paren-newline
export default async function generator(
    actionYmlFile: string, outFile: string, watch: boolean, lineWrap?: number): Promise<void> {
    if (![ ".yml", ".yaml" ].includes(path.extname(actionYmlFile))) {
        logger.log(`Warning: ${actionYmlFile} does not appear to be a yaml file.`);
    }

    await generateInner(actionYmlFile, outFile, lineWrap);

    if (!watch) {
        // Done
        return;
    }

    logger.log(`Watching ${actionYmlFile} for further changes (CTRL + C to exit)...`);

    let modifyingProm: Promise<unknown> | undefined;

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    fs.watch(actionYmlFile, async (_event: string, _filename: string | null) => {
        logger.log(`${actionYmlFile} changed`);

        if (modifyingProm) {
            logger.log(`Update already in progress, waiting...`);
            await modifyingProm;
            logger.log(`Done waiting`);
        }

        modifyingProm = generateInner(actionYmlFile, outFile, lineWrap)
            .catch((err) => {
                console.error(err);
            })
            .finally(() => {
                modifyingProm = undefined;
            });
    });
}

async function generateInner(actionYmlFile: string, outFile: string, lineWrap?: number): Promise<void> {
    const actionYml = await loadActionYml(actionYmlFile);

    const inputs = Object.entries(actionYml.inputs || []);
    const outputs = Object.entries(actionYml.outputs || []);

    logger.log(
        `Found ${inputs.length} input${inputs.length === 1 ? "" : "s"} `
        + `and ${outputs.length} output${outputs.length === 1 ? "" : "s"}.`,
    );

    await outputEnums(outFile, inputs, outputs, lineWrap);
}

async function loadActionYml(actionYmlFile: string): Promise<ActionYml> {
    const actionYmlContents = (await promisify(fs.readFile)(actionYmlFile)).toString();

    const actionYmlRaw = jsYaml.load(actionYmlContents);

    if (actionYmlRaw == null) {
        throw new Error(`Action yaml load returned ${actionYmlRaw}`);
    }
    else if (typeof actionYmlRaw === "string") {
        throw new Error(`Failed to parse ${actionYmlFile} as yaml`);
    }

    const actionYml = actionYmlRaw as ActionYml;
    return actionYml;
}

// eslint-disable-next-line function-paren-newline
async function outputEnums(
    outFile: string, inputs: InputOutputEntries, outputs: InputOutputEntries, lineWrap?: number): Promise<void> {
    let outputFileContents = `// This file was auto-generated by action-io-generator. Do not edit by hand!\n`;
    outputFileContents += enumify("Inputs", inputs, lineWrap);
    outputFileContents += `\n`;
    outputFileContents += enumify("Outputs", outputs, lineWrap);

    await promisify(fs.writeFile)(outFile, outputFileContents);
    logger.log(`Output input and output enums to ${outFile}`);
}

function wordWrap(text: string, maxWidth: number, prefix: string): string {
    const words = text.split(/\s+/);
    const lines: string[] = [];
    let currentLine = "";
    const firstLineMax = maxWidth - prefix.length - 1;

    for (const word of words) {
        if (currentLine === "") {
            currentLine = word;
        }
        else {
            const candidate = `${currentLine} ${word}`;
            const limit = lines.length === 0 ? firstLineMax : maxWidth;
            if (candidate.length > limit) {
                lines.push(currentLine);
                currentLine = word;
            }
            else {
                currentLine = candidate;
            }
        }
    }
    lines.push(currentLine);

    return lines.map((line: string, i: number) => (i === 0 ? line : `${prefix} ${line}`)).join("\n");
}

function enumify(enumName: string, inputsOrOutputs: [string, InputOrOutput][], lineWrap?: number): string {
    inputsOrOutputs.sort();

    const OUTPUT_INDENT = " ".repeat(4);
    const LINE_START = `${OUTPUT_INDENT} *`;

    return inputsOrOutputs.reduce((accumulator, [ name, props ]) => {
        let foldedDescription = props.description.trim()
            .replace(/\r\n/g, `\n`)                     // want windows line endings? too bad
            .replace(/[\r\n]/g, `\n${LINE_START} `);

        if (lineWrap != null) {
            foldedDescription = foldedDescription.split(`\n${LINE_START} `)
                .map((paragraph: string, i: number) => {
                    const wrapped = wordWrap(paragraph, lineWrap, LINE_START);
                    return i === 0 ? wrapped : `${LINE_START} ${wrapped}`;
                })
                .join("\n");
        }

        const enumifiedName = name.toUpperCase().replace(/-/g, "_");

        // eslint-disable-next-line no-param-reassign,operator-linebreak
        accumulator +=
`${OUTPUT_INDENT}/**
${LINE_START} ${foldedDescription}
${LINE_START} Required: ${!!props.required}
${LINE_START} Default: ${props.default !== undefined ? `"${props.default}"` : "None."}
${LINE_START}/
${OUTPUT_INDENT}${enumifiedName} = "${name}",
`;
        return accumulator;
    }, `export enum ${enumName} {\n`) + `}\n`;
}
