
name: action-io-generator CI
on:
  push:
  pull_request:

defaults:
  run:
    working-directory: action-io-generator

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
  
  check-dist:
    name: Check Distribution
    runs-on: ubuntu-20.04
    env:
      BUNDLE_FILE: "dist/bin.js"
      BUNDLE_COMMAND: "npm run bundle"
      WORKDIR: "./action-io-generator"
    steps:
      - uses: actions/checkout@v2

      - name: Install
        working-directory: ${{ env.WORKDIR }}
        run: npm ci

      - name: Verify Latest Bundle
        uses: redhat-actions/common/bundle-verifier@v1
        with:
          bundle_file: ${{ env.BUNDLE_FILE }}
          bundle_command: ${{ env.BUNDLE_COMMAND }}
          working_directory: ${{ env.WORKDIR }}
  
  compile_test:
    name: Compile and test
    runs-on: ubuntu-20.04
    env:
      TEST_FILE: test/generated/inputs-outputs.ts

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run lint
      - run: npm run compile
      - run: npm run bundle

      ##### End compile steps

      - name: Prepare to test
        run: rm -v ${{ env.TEST_FILE }}

      - name: Test action-io-generator CLI
        run: npm run test-cli

      - name: Sniff test new enum file
        shell: bash
        run: |
          set -x
          [[ -f ${{ env.TEST_FILE }} ]]
          grep "export enum Inputs" ${{ env.TEST_FILE }}
          grep "export enum Outputs" ${{ env.TEST_FILE }}
          LINES=$(wc -l ${{ env.TEST_FILE }} | awk '{ print $1 }')
          (( LINES > 30 ))

      - name: Debug failed test
        if: failure()
        run: cat ${{ env.TEST_FILE }}

      - name: Clean up again
        if: always()
        run: rm -v ${{ env.TEST_FILE }}

      ##### End test steps
