name: commit-data CI
on:
  push:
    branches: [main]
    paths:
      - 'commit-data/**'
      - '.github/workflows/ci-commit-data.yml'
  pull_request:
    paths:
      - 'commit-data/**'
      - '.github/workflows/ci-commit-data.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit_data:
    name: Get Commit Data
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.commit_data.outputs.tag }}

    steps:
      - uses: actions/checkout@v7

      - name: Run commit-data
        id: commit_data
        uses: ./commit-data/

      - name: Echo outputs
        run: echo "${{ toJSON(steps.commit_data.outputs) }}"
